questions =  [
    {"id": 0, "question": "경제활동의 자유는 사회가 번창할 수 있는 최선의 현실적인 방법이다. Freedom of business is the best practical way a society can prosper.", "effects": {"right": 1}},
    {"id": 1, "question": "기부는 사회복지제도보다 어려움에 처한 이들을 돕는 더 좋은 방법이다. Charity is a better way of helping those in need than social welfare.", "effects": {"right": 1}},
    {"id": 2, "question": "고용주들이 노동자들의 노동가치를 가장 잘 파악하고 있기에, 그들이 책정한 임금은 항상 적절하다. Wages are always fair, as employers know best what a worker's labour is worth.", "effects": {"right": 1}},
    {"id": 3, "question": "탐욕은 인간의 본성이다. It is \"human nature\" to be greedy.", "effects": {"right": 1}},
    {"id": 4, "question": "1800년대 당시 자본주의의 문제점들이 더 이상 존재하지 않으므로, 착취라는 용어는 시대에 맞지 않는다. \"Exploitation\" is an outdated term, as the struggles of 1800s capitalism don't exist anymore.", "effects": {"right": 1}},
    {"id": 5, "question": "공산주의는 현실에서 작동하지 않는 이상이다. Communism is an ideal that can never work in practice.", "effects": {"right": 1}},
    {"id": 6, "question": "부자에 대한 과세는 나쁘며, 부자에 대한 과세가 없는 사회가 더 나은 사회일 것이다. Taxation of the wealthy is a bad idea, society would be better off without it.", "effects": {"right": 1}},
    {"id": 7, "question": "열심히 일할수록 사회계층을 더 올라갈 수 있다. The harder you work, the more you progress up the social ladder.", "effects": {"right": 1}},
    {"id": 8, "question": "단체와 회사들은 믿을 수 없으며 정부에 의해 규제되어야 한다. Organisations and corporations cannot be trusted and need to be regulated by the government.", "effects": {"right": -1}},
    {"id": 9, "question": "사회구성원을 모두 부양하는 정부의 시스템은 근본적으로 좋은 아이디어이다. A government that provides for everyone is an inherently good idea.", "effects": {"right": -1}},
    {"id": 10, "question": "현재의 사회복지제도는 빈부격차를 줄이기 위해 더욱더 확장되어야 한다. The current welfare system should be expanded to further combat inequality.", "effects": {"right": -1}},
    {"id": 11, "question": "토지는 사고팔 수 있는 상품이어서는 안된다. Land should not be a commodity to be bought and sold.", "effects": {"right": -1}},
    {"id": 12, "question": "모든 산업과 은행은 국유화되어야 한다. All industry and the bank should be nationalised.", "effects": {"right": -1}},
    {"id": 13, "question": "계층은 사회의 주된 구분체계이다. Class is the primary division of society.", "effects": {"right": -1}},
    {"id": 14, "question": "빈부격차가 세계적으로 너무 심하다. Economic inequality is too high in the world.", "effects": {"right": -1}},
    {"id": 15, "question": "정부가 극단주의자와 테러리스트들에게 대응하기 위해 시민들을 감시하는 것은 어떤 때는 옳은 조치이다. Sometimes it is right that the government may spy on its citizens to combat extremists and terrorists.", "effects": {"auth": 1}},
    {"id": 16, "question": "도덕적으로 올바른 권위주의적인 인물은 사회에게 좋다. Authority figures, if morally correct, are a good thing for society.", "effects": {"auth": 1}},
    {"id": 17, "question": "어느 정부든 성공하기 위해서는 권력이 필요하다. Strength is necessary for any government to succeed.", "effects": {"auth": 1}},
    {"id": 18, "question": "정부만이 단체들을 공정하고 올바르게 규제할 수 있다. Only the government can fairly and effectively regulate organisations.", "effects": {"auth": 1}},
    {"id": 19, "question": "사회는 기능하기 위해서 행정과 제도가 필요하다. Society requires structure and bureaucracy in order to function.", "effects": {"auth": 1}},
    {"id": 20, "question": "공공안녕을 위해 (기본적인 생활에 없으면 안되는)필수신분증이 사용되어야 한다. Mandatory IDs should be used to ensure public safety.", "effects": {"auth": 1}},
    {"id": 21, "question": "위기 상황에서는 시민 자유(민권)보다 안전이 중요해진다. In times of crisis, safety becomes more important than civil liberties.", "effects": {"auth": 1}},
    {"id": 22, "question": "숨길 게 없다면 무서워할 것도 없다. If you have nothing to hide, you have nothing to fear.", "effects": {"auth": 1}},
    {"id": 23, "question": "정부는 시민들의 일상생활에 덜 관여해야 한다. The government should be less involved in the day to day life of its citizens.", "effects": {"auth": -1}},
    {"id": 24, "question": "민주주의 없이 사회는 아무것도 아니다. Without democracy, a society is nothing.", "effects": {"auth": -1}},
    {"id": 25, "question": "형사재판에서 피고인이 범법을 저질렀더라도 배심원단이 무죄를 선고하는 것(배심원 무효화)은 합법이어야 한다. Jury nullification should be legal.", "effects": {"auth": -1}},
    {"id": 26, "question": "작은 정부일수록 시민들은 자유롭다. The smaller the government, the freer the people.", "effects": {"auth": -1}},
    {"id": 27, "question": "정부는 긴급서비스와 법률집행 이상으로 권한을 행사해서는 안된다. The government should, at most, provide emergency services and law enforcement.", "effects": {"auth": -1}},
    {"id": 28, "question": "경찰은 시민을 보호하기보다는 무력으로 현상을 유지하기 위해 생겼다.The police were not created to protect the people, but to uphold the status quo by force.", "effects": {"auth": -1}},
    {"id": 29, "question": "국가가 어린이들에게 영향을 끼쳐서는 안되기에 공립학교는 나쁜 제도이다. State schools are a bad idea because our state shouldn't be influencing our children.", "effects": {"auth": -1}},
    {"id": 30, "question": "설사 내가 불편하다고 느끼는 것이라도, 상호동의 하에 두 사람은 서로에게 무엇이든 할 수 있어야 한다. Two consenting individuals should be able to do whatever they want with each other, even if it makes me uncomfortable.", "effects": {"prog": 1}},
    {"id": 31, "question": "개인의 신체는 그들 자신의 소유물로, 그들은 그들이 원하는 무엇이든 신체에 행할 수 있어야 한다. An individual's body is their own property, and they should be able to do anything they desire to it.", "effects": {"prog": 1}},
    {"id": 32, "question": "개인은 누구 또는 무엇이든 간에 믿고 싶은 것을 믿을 수 있어야 한다. A person should be able to worship whomever or whatever they want.", "effects": {"prog": 1}},
    {"id": 33, "question": "나체주의는 매우 자연스러운 것이다. Nudism is perfectly natural.", "effects": {"prog": 1}},
    {"id": 34, "question": "동물들은 몇몇 보편적인 권리를 인정받아야 한다. Animals deserve certain universal rights.", "effects": {"prog": 1}},
    {"id": 35, "question": "젠더는 사회적인 합의체지, 자연 그대로의 상태가 아니다. Gender is a social construct, not a natural state of affairs.", "effects": {"prog": 1}},
    {"id": 36, "question": "윤리 대신 전통적인 가치에 바탕을 둔 법은 정의롭지 못하다. Laws based on cultural values, rather than ethical ones, aren't justice.", "effects": {"prog": 1}},
    {"id": 37, "question": "미성년자, 정신질환자, 그리고 중범죄자도 신체의 자주성을 지닌다. Autonomy of body extends even to minors, the mentally ill, and serious criminals.", "effects": {"prog": 1}},
    {"id": 38, "question": "동성애는 내 사상에 반한다. Homosexuality is against my values.", "effects": {"prog": -1}},
    {"id": 39, "question": "트렌스젠더들은 어린이를 입양할 수 있어서는 안된다. Transgender individuals should not be able to adopt children.", "effects": {"prog": -1}},
    {"id": 40, "question": "마약은 해로우며 금지되어야 한다. Drugs are harmful and should be banned.", "effects": {"prog": -1}},
    {"id": 41, "question": "사형제도는 몇몇 범죄에 대해서는 존재해야 한다. The death penalty should exist for certain crimes.", "effects": {"prog": -1}},
    {"id": 42, "question": "범죄행위의 피해자가 없더라도 범죄는 처벌받아야 한다. Victimless crimes should still be punished.", "effects": {"prog": -1}},
    {"id": 43, "question": "종교 없이는 도덕적일 수 없다. One cannot be moral without religion.", "effects": {"prog": -1}},
    {"id": 44, "question": "부모들은 연륜이 많기 때문에, 그들의 자식들에 대해서 절대적인 권한을 쥐고 있어야 한다. Parents should hold absolute power over their children, as they are older and more experienced.", "effects": {"prog": -1}},
    {"id": 45, "question": "다문화주의는 나쁘다. Multiculturalism is bad.", "effects": {"prog": -1}}
];
