questions =  [
    {"id": 0, "question": "사회가 성장하는 가장 현실적인 방법은 사업 규제를 철폐하는 것이다.", "effects": {"right": 1}},
    {"id": 1, "question": "빈자들을 돕는 방법으로는 사회복지제도보다 자선기부가 낫다.", "effects": {"right": 1}},
    {"id": 2, "question": "노동의 가치는 고용주가 가장 잘 알기에, 고용주가 책정한 임금은 항상 적절하다.", "effects": {"right": 1}},
    {"id": 3, "question": "탐욕은 인간의 본성이다.", "effects": {"right": 1}},
    {"id": 4, "question": "19세기 자본주의의 문제점들은 해결되었으므로, 착취라는 용어는 시대에 맞지 않는다.", "effects": {"right": 1}},
    {"id": 5, "question": "공산주의는 현실에서 작동하지 않는 공상적 사상이다.", "effects": {"right": 1}},
    {"id": 6, "question": "고소득층에 대한 과세는 나쁜 생각이며, 사회에 악영향을 미친다.", "effects": {"right": 1}},
    {"id": 7, "question": "열심히 일하면 자신의 사회적 계층도 올라갈 수 있다.", "effects": {"right": 1}},
    {"id": 8, "question": "기업과 회사는 신뢰할 수 없으므로 정부에 의한 규제가 필수적이다.", "effects": {"right": -1}},
    {"id": 9, "question": "모든 사회구성원을 부양하는 정부라는 개념은 좋은 생각이다.", "effects": {"right": -1}},
    {"id": 10, "question": "빈부격차를 줄이기 위해, 사회복지제도는 현재보다 확장되어야 한다.", "effects": {"right": -1}},
    {"id": 11, "question": "토지는 사고팔 수 있는 재산이어서는 안된다.", "effects": {"right": -1}},
    {"id": 12, "question": "모든 산업과 은행은 국유화되어야 한다.", "effects": {"right": -1}},
    {"id": 13, "question": "근본적으로, 사회는 계급으로 구분지을 수 있다.", "effects": {"right": -1}},
    {"id": 14, "question": "빈부격차가 세계적으로 너무 심하다.", "effects": {"right": -1}},
    {"id": 15, "question": "상황에 따라, 정부는 극단주의자와 간첩에게 대응하기 위해 국민을 감시할 수 있다.", "effects": {"auth": 1}},
    {"id": 16, "question": "도덕적인 권력자가 있으면 사회에 도움이 된다.", "effects": {"auth": 1}},
    {"id": 17, "question": "어느 정부든 성공하기 위해서는 권력이 필요하다.", "effects": {"auth": 1}},
    {"id": 18, "question": "정부만이 단체를 공정하고 올바르게 규제할 수 있다.", "effects": {"auth": 1}},
    {"id": 19, "question": "제도와 관료제 없는 사회는 제대로 기능할 수 없다.", "effects": {"auth": 1}},
    {"id": 20, "question": "공공안녕을 위해서 신분증 발급이 강제되어야 한다.", "effects": {"auth": 1}},
    {"id": 21, "question": "위기 상황에서는 안보가 권리에 우선한다.", "effects": {"auth": 1}},
    {"id": 22, "question": "숨길 것이 없다면 무서워할 것도 없다.", "effects": {"auth": 1}},
    {"id": 23, "question": "정부는 국민의 일상생활에 덜 관여해야 한다.", "effects": {"auth": -1}},
    {"id": 24, "question": "민주주의 없는 사회는 의미가 없다.", "effects": {"auth": -1}},
    {"id": 25, "question": "피고인이 범죄를 저질렀더라도 상황에 따라 배심원들이 무죄를 선고할 수 있어야 한다.", "effects": {"auth": -1}},
    {"id": 26, "question": "정부가 작을수록 국민은 자유롭다.", "effects": {"auth": -1}},
    {"id": 27, "question": "정부의 역할은 최대 긴급 구조와 법률 집행으로 제한되어야 한다.", "effects": {"auth": -1}},
    {"id": 28, "question": "경찰이 생겨난 본질적인 이유는 시민 보호가 아니라 무력을 통한 현상 유지이다.", "effects": {"auth": -1}},
    {"id": 29, "question": "국가가 어린이들에게 영향을 끼쳐서는 안되기에 공립학교는 나쁜 제도이다.", "effects": {"auth": -1}},
    {"id": 30, "question": "개인 간 합의 하에 이뤄지는 모든 행동은, 내가 불편하다고 느끼는 행동이더라도, 간섭 받아서는 안된다.", "effects": {"prog": 1}},
    {"id": 31, "question": "신체는 개인의 소유물이므로, 개인은 신체에 원하는 무엇이든 할 권리가 있다.", "effects": {"prog": 1}},
    {"id": 32, "question": "개인은 원하는 무엇이든 숭배할 수 있어야 한다.", "effects": {"prog": 1}},
    {"id": 33, "question": "나체주의는 매우 자연스러운 것이다.", "effects": {"prog": 1}},
    {"id": 34, "question": "동물은 몇몇 보편적인 권리를 인정받아야 한다.", "effects": {"prog": 1}},
    {"id": 35, "question": "젠더는 사회가 개인에게 부과한 것이지, 자연적으로 주어지는 것이 아니다.", "effects": {"prog": 1}},
    {"id": 36, "question": "윤리적 가치가 아닌 전통적인 가치에 바탕을 둔 법은 정의롭지 못하다.", "effects": {"prog": 1}},
    {"id": 37, "question": "미성년자, 정신질환자, 중범죄자에게도 신체의 자유는 보장된다.", "effects": {"prog": 1}},
    {"id": 38, "question": "동성애는 내 사상에 반한다.", "effects": {"prog": -1}},
    {"id": 39, "question": "트렌스젠더에게 어린이를 입양할 권리를 주어서는 안된다.", "effects": {"prog": -1}},
    {"id": 40, "question": "마약은 해로우며 금지되어야 한다.", "effects": {"prog": -1}},
    {"id": 41, "question": "어떤 범죄에 대한 사형제도는 존재해야 한다.", "effects": {"prog": -1}},
    {"id": 42, "question": "피해자 없는 범죄도 처벌받아야 한다.", "effects": {"prog": -1}},
    {"id": 43, "question": "종교 없이는 도덕적일 수 없다.", "effects": {"prog": -1}},
    {"id": 44, "question": "부모는 연륜이 있으므로, 그들의 자식들에 대해서 절대적인 권한을 쥐고 있어야 한다.", "effects": {"prog": -1}},
    {"id": 45, "question": "다문화주의는 득보다 실이 많다.", "effects": {"prog": -1}}
];
